[package]
name = "kvs"
version = "0.1.0"
authors = ["kuronyago <yegor.pesterev@gmail.com>"]
description = "A key-value store"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
structopt = "0.3.9"
failure = "0.1.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"
log = "0.4.8"
env_logger = "0.7.1"
sled = "0.31.0"